DROP TABLE IF EXISTS Feedbacks;
DROP TABLE IF EXISTS Sensations;
DROP TABLE IF EXISTS Coments;
DROP TABLE IF EXISTS TemplateRows;
DROP TABLE IF EXISTS Templates;
DROP TABLE IF EXISTS TrainingCycles;
DROP TABLE IF EXISTS ClientServices;
DROP TABLE IF EXISTS Services;
DROP TABLE IF EXISTS PersonalBests;
DROP TABLE IF EXISTS Weights;
DROP TABLE IF EXISTS Exercises;
DROP TABLE IF EXISTS Users;

-- El campo userRole guarda un 0 si es TRAINER y un 1 si es CLIENT.
CREATE TABLE Users (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL, 
    fullName VARCHAR(60) NOT NULL,
    phone VARCHAR(15),
    icon VARCHAR(255),
    userRole TINYINT NOT NULL,
    socialLinks VARCHAR(1000),
    birthdate DATE,
    injuries VARCHAR(500),
    goals VARCHAR(500),
    height NUMERIC(5,2),
    trainerId BIGINT,
    CONSTRAINT trainerClientsIdFK FOREIGN KEY(trainerId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Services (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    service VARCHAR(255) NOT NULL,
    price NUMERIC(5,2),
    trainerId BIGINT NOT NULL,
    CONSTRAINT trainerServicesIdFK FOREIGN KEY(trainerId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE ClientServices (
    clientId BIGINT NOT NULL,
    serviceId BIGINT NOT NULL,
    PRIMARY KEY (clientId, serviceId),
    CONSTRAINT clientServicesIdFK FOREIGN KEY(clientId) REFERENCES Users(id) ON DELETE CASCADE,
    CONSTRAINT serviceClientsIdFK FOREIGN KEY(serviceId) REFERENCES Services(id) ON DELETE CASCADE
);

CREATE TABLE TrainingCycles (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cycleName VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    fromDate DATE NOT NULL,
    toDate DATE NOT NULL,
    trainerId BIGINT NOT NULL,
    clientId BIGINT NOT NULL,
    CONSTRAINT trainerCyclesIdFK FOREIGN KEY(trainerId) REFERENCES Users(id) ON DELETE CASCADE,
    CONSTRAINT clientCyclesIdFK FOREIGN KEY(clientId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Exercises (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    exerciseName VARCHAR(255) NOT NULL,
    description VARCHAR(500) NOT NULL,
    exerciseType VARCHAR(255) NOT NULL,
    bodyPart VARCHAR(255),
    equipment VARCHAR(255),
    exerciseLink VARCHAR(1000),
    trainerId BIGINT,
    CONSTRAINT trainerExercisesIdFK FOREIGN KEY(trainerId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Templates (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    templateName VARCHAR(255) NOT NULL,
    templateDate TIMESTAMP NOT NULL,
    cycleId BIGINT NOT NULL,
    CONSTRAINT cycleTemplatesIdFK FOREIGN KEY(cycleId) REFERENCES TrainingCycles(id) ON DELETE CASCADE
);

CREATE TABLE TemplateRows (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    series TINYINT,
    repetitions TINYINT,
    weight NUMERIC(5,2),
    exerciseId BIGINT NOT NULL,
    templateId BIGINT NOT NULL,
    CONSTRAINT exerciseRowsIdFK FOREIGN KEY(exerciseId) REFERENCES Exercises(id) ON DELETE CASCADE,
    CONSTRAINT templateRowsIdFK FOREIGN KEY(templateId) REFERENCES Templates(id) ON DELETE CASCADE
);

CREATE TABLE Coments (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    comentDate TIMESTAMP NOT NULL,
    templateId BIGINT,
    userId BIGINT NOT NULL,
    CONSTRAINT templateComentsIdFK FOREIGN KEY(templateId) REFERENCES Templates(id) ON DELETE CASCADE,
    CONSTRAINT userComentsIdFK FOREIGN KEY(userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Sensations (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fatigue TINYINT,
    stiffness TINYINT,
    motivation TINYINT,
    sleep TINYINT,
    sensationDate TIMESTAMP NOT NULL,
    templateId BIGINT NOT NULL,
    userId BIGINT NOT NULL,
    CONSTRAINT templateSensationsIdFK FOREIGN KEY(templateId) REFERENCES Templates(id) ON DELETE CASCADE,
    CONSTRAINT userSensationsIdFK FOREIGN KEY(userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Weights (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    weight NUMERIC(5,2) NOT NULL,
    weightDate TIMESTAMP NOT NULL,
    clientId BIGINT NOT NULL,
    CONSTRAINT clientWeightsIdFK FOREIGN KEY(clientId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE PersonalBests (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    weight NUMERIC(5,2) NOT NULL,
    bestDate TIMESTAMP NOT NULL,
    exerciseId BIGINT NOT NULL,
    clientId BIGINT NOT NULL,
    CONSTRAINT exerciseBestsIdFK FOREIGN KEY(exerciseId) REFERENCES Exercises(id) ON DELETE CASCADE,
    CONSTRAINT clientBestsIdFK FOREIGN KEY(clientId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Feedbacks (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    feedbackFile VARCHAR(255) NOT NULL,
    feedbackDate TIMESTAMP NOT NULL,
    templateId BIGINT NOT NULL,
    clientId BIGINT NOT NULL,
    CONSTRAINT templateFeedbacksIdFK FOREIGN KEY(templateId) REFERENCES Templates(id) ON DELETE CASCADE,
    CONSTRAINT clientFeedbacksIdFK FOREIGN KEY(clientId) REFERENCES Users(id) ON DELETE CASCADE
);
